simple auto score and auto intake
Team3256/FRC_Programming_2023 pull request #211
Opened 2023-03-15 18:43 UTC by adityapawar1

## Checklist

- [x] I have read the [Contributing](Contributing.md) document.

- [ ] If code changes were made then they have been tested.

## Summary

2023-03-15 21:11 UTC, viveknadig282 requested changes

2023-03-16 22:36 UTC, 3LucasZ approved these changes
Looks good. Hopefully we can merge after we test It IRL. I have confidence.

2023-03-16 22:43 UTC, 3LucasZ approved these changes

2023-03-19 05:38 UTC, abalakrishnan1 requested changes

2023-03-20 01:24 UTC, abalakrishnan1 approved these changes

2023-03-25 21:37 UTC, viveknadig282 requested changes

2023-03-26 05:20 UTC, merged