Feat/ground intake subsystem
Team3256/FRC_Programming_2023 pull request #216
Opened 2023-03-19 04:32 UTC by WilliamT424

## Checklist

- [x] I have read the [Contributing](Contributing.md) document.

- [ ] If code changes were made then they have been tested.

## Summary

This pull request is for the Mole subsystem which will be a ground intake on our robot. This subsystem will have 2 falcon motors and will use one for the intake wheels and one for a pivot. There are also 3 presets for easy use (Low also for intaking cubes, mid, high) and LEDs (need to change probably to show correct things if its implemented)to go along. The code has not been testing and the CAN IDs are random right now.

2023-03-20 23:28 UTC, akhil-datla approved these changes

2023-03-22 02:07 UTC, adityapawar1 requested changes

2023-03-22 17:27 UTC, adityapawar1 approved these changes
Looks good so far, lmk when interpolation is coded in and I can review that

2023-03-23 04:17 UTC, adityapawar1 requested changes

2023-03-26 20:05 UTC, closed without merging